package ph.edu.cdsga.sms.ums.utils.string;

public class TraceLog {

    TraceLog() {
        throw new IllegalStateException("Utility class");
    }

    public static final String SMS_AUTHENTICATION_CONTROLLER_AUTHENTICATE = "SMS_AUTHENTICATION_CONTROLLER_AUTHENTICATE";
    public static final String SMS_REGISTRATION_CONTROLLER_REGISTER_ACCOUNT = "SMS_REGISTRATION_CONTROLLER_REGISTER_ACCOUNT";
    public static final String SMS_REGISTRATION_CONTROLLER_ACTIVATE_ACCOUNT = "SMS_REGISTRATION_CONTROLLER_ACTIVATE_ACCOUNT";

    public static final String SMS_AUTHENTICATION_SERVICE_AUTHENTICATE = "SMS_AUTHENTICATION_SERVICE_AUTHENTICATE";
    public static final String SMS_REGISTRATION_SERVICE_REGISTER_ACCOUNT = "SMS_REGISTRATION_SERVICE_REGISTER_ACCOUNT";
}
